project:
  type: website
  output-dir: docs

website:
  navbar:
    background: "#2C3E50"
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: portfolio.qmd
        text: Projects
  page-footer:
    center: "Copyright &copy; 2024 ECOMOD. All rights reserved."
    background: light
  favicon: favicon.ico

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

execute:
  echo: false
  warning: false
  error: true
  cache: true



