project:
  type: website
  output-dir: docs

website:
  navbar:
    background: "#2C3E50"
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: projects.qmd
        text: Projects
      - href: activities.qmd
        text: Activities
      - href: publications.qmd
        text: Publications
  page-footer:
    left: "Copyright &copy; 2025 ECOMOD. All rights reserved."
    right: "Built with [Quarto](https://quarto.org/)"
    background: light
  favicon: favicon.ico

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

execute:
  echo: false
  warning: false
  error: true
  cache: true

# see https://quarto.org/docs/websites/website-listings.html
listing:
  contents: 
    - "publications/*.qmd" 
  categories: cloud
  sort: "year desc"
  filter-ui: true
